CREATE DATABASE DT_LIVRO;
USE DT_LIVRO;

CREATE TABLE TBL_LIVRO
(ID_LIVRO 	  BIGINT auto_increment PRIMARY KEY NOT NULL,
TITULO_LIVRO  VARCHAR(45) NOT NULL,
AUTOR_LIVRO   VARCHAR(45) NOT NULL,
EDITORA_LIVRO VARCHAR(45) NOT NULL,
CATEGORIA	  VARCHAR(20)     NOT NULL,
QUANTIDADE    INT         NOT NULL);

drop table TBL_LIVRO